/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type ApiKeyTransformer from '#transformers/api_key_transformer'
import type HealthResultTransformer from '#transformers/health_result_transformer'
import type ProxyEntryTransformer from '#transformers/proxy_entry_transformer'
import type ProxyListTransformer from '#transformers/proxy_list_transformer'
import type ProxyUsageLogTransformer from '#transformers/proxy_usage_log_transformer'
import type RotationConfigTransformer from '#transformers/rotation_config_transformer'
import type ScraperSourceTransformer from '#transformers/scraper_source_transformer'
import type TeamTransformer from '#transformers/team_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type ApiKey = InferData<ApiKeyTransformer>
  export namespace ApiKey {
    export type Variants = InferVariants<ApiKeyTransformer>
  }
  export type HealthResult = InferData<HealthResultTransformer>
  export namespace HealthResult {
    export type Variants = InferVariants<HealthResultTransformer>
  }
  export type ProxyEntry = InferData<ProxyEntryTransformer>
  export namespace ProxyEntry {
    export type Variants = InferVariants<ProxyEntryTransformer>
  }
  export type ProxyList = InferData<ProxyListTransformer>
  export namespace ProxyList {
    export type Variants = InferVariants<ProxyListTransformer>
  }
  export type ProxyUsageLog = InferData<ProxyUsageLogTransformer>
  export namespace ProxyUsageLog {
    export type Variants = InferVariants<ProxyUsageLogTransformer>
  }
  export type RotationConfig = InferData<RotationConfigTransformer>
  export namespace RotationConfig {
    export type Variants = InferVariants<RotationConfigTransformer>
  }
  export type ScraperSource = InferData<ScraperSourceTransformer>
  export namespace ScraperSource {
    export type Variants = InferVariants<ScraperSourceTransformer>
  }
  export type Team = InferData<TeamTransformer>
  export namespace Team {
    export type Variants = InferVariants<TeamTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
