/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Admin: () => import('#controllers/admin_controller'),
  ApiKeys: () => import('#controllers/api_keys_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  HealthChecker: () => import('#controllers/health_checker_controller'),
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  ProxyEntries: () => import('#controllers/proxy_entries_controller'),
  ProxyLists: () => import('#controllers/proxy_lists_controller'),
  ProxyUsageAnalytics: () => import('#controllers/proxy_usage_analytics_controller'),
  ScraperSources: () => import('#controllers/scraper_sources_controller'),
  Session: () => import('#controllers/session_controller'),
  Teams: () => import('#controllers/teams_controller'),
  ToolsChecker: () => import('#controllers/tools_checker_controller'),
}
