/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import HealthCheckCompleted from '#events/health_check_completed'
import ProxyImported from '#events/proxy_imported'

export const events = {
  HealthCheckCompleted: HealthCheckCompleted,
  ProxyImported: ProxyImported,
}
