/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApiKeySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastUsedAt', 'monthlyQuotaBytes', 'name', 'revokedAt', 'teamId', 'tokenHash', 'tokenPrefix', 'updatedAt', 'userId'] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare monthlyQuotaBytes: bigint | number | null
  @column()
  declare name: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare teamId: number
  @column()
  declare tokenHash: string
  @column()
  declare tokenPrefix: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class HealthCheckRunSchema extends BaseModel {
  static $columns = ['checkedCount', 'createdAt', 'errorMessage', 'finishedAt', 'healthyCount', 'id', 'invalidCount', 'meta', 'mode', 'proxyListId', 'sourceType', 'startedAt', 'status', 'targetUrl', 'teamId', 'timeoutCount', 'totalInputs', 'unhealthyCount', 'updatedAt'] as const
  $columns = HealthCheckRunSchema.$columns
  @column()
  declare checkedCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare healthyCount: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invalidCount: number
  @column()
  declare meta: any | null
  @column()
  declare mode: string
  @column()
  declare proxyListId: number | null
  @column()
  declare sourceType: string
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column()
  declare targetUrl: string | null
  @column()
  declare teamId: number
  @column()
  declare timeoutCount: number
  @column()
  declare totalInputs: number
  @column()
  declare unhealthyCount: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class HealthResultSchema extends BaseModel {
  static $columns = ['checkedAt', 'createdAt', 'errorMessage', 'healthy', 'id', 'latencyMs', 'mode', 'proxyEntryId', 'resolvedAt', 'resolvedByRunId', 'returnedIp', 'statusCode', 'updatedAt'] as const
  $columns = HealthResultSchema.$columns
  @column.dateTime()
  declare checkedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column()
  declare healthy: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latencyMs: number | null
  @column()
  declare mode: string
  @column()
  declare proxyEntryId: number
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare resolvedByRunId: number | null
  @column()
  declare returnedIp: string | null
  @column()
  declare statusCode: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProxyEntrySchema extends BaseModel {
  static $columns = ['asnNumber', 'countryCode', 'createdAt', 'host', 'id', 'lastCheckedAt', 'latencyMs', 'password', 'port', 'protocol', 'proxyListId', 'returnedIp', 'source', 'status', 'updatedAt', 'username'] as const
  $columns = ProxyEntrySchema.$columns
  @column()
  declare asnNumber: number | null
  @column()
  declare countryCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare host: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastCheckedAt: DateTime | null
  @column()
  declare latencyMs: number | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare port: number
  @column()
  declare protocol: string
  @column()
  declare proxyListId: number
  @column()
  declare returnedIp: string | null
  @column()
  declare source: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}

export class ProxyListSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'name', 'teamId', 'updatedAt'] as const
  $columns = ProxyListSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProxyUsageLogSchema extends BaseModel {
  static $columns = ['apiKeyId', 'attemptCount', 'countryOverride', 'createdAt', 'durationMs', 'errorMessage', 'id', 'isTunnel', 'proxyEntryId', 'proxyListId', 'requestMethod', 'requestedAt', 'responseBytes', 'selectedAsn', 'selectedCountry', 'selectedProtocol', 'sessionKey', 'statusCode', 'success', 'targetHost', 'targetPort', 'targetScheme', 'teamId', 'updatedAt'] as const
  $columns = ProxyUsageLogSchema.$columns
  @column()
  declare apiKeyId: number | null
  @column()
  declare attemptCount: number
  @column()
  declare countryOverride: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isTunnel: boolean
  @column()
  declare proxyEntryId: number | null
  @column()
  declare proxyListId: number | null
  @column()
  declare requestMethod: string
  @column.dateTime()
  declare requestedAt: DateTime
  @column()
  declare responseBytes: bigint | number
  @column()
  declare selectedAsn: number | null
  @column()
  declare selectedCountry: string | null
  @column()
  declare selectedProtocol: string | null
  @column()
  declare sessionKey: string | null
  @column()
  declare statusCode: number | null
  @column()
  declare success: boolean
  @column()
  declare targetHost: string | null
  @column()
  declare targetPort: number | null
  @column()
  declare targetScheme: string | null
  @column()
  declare teamId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'level', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RotationConfigSchema extends BaseModel {
  static $columns = ['createdAt', 'excludeAsn', 'excludeCountries', 'geoTarget', 'id', 'intervalMinutes', 'protocol', 'proxyListId', 'rotationType', 'stickyDurationMinutes', 'updatedAt'] as const
  $columns = RotationConfigSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare excludeAsn: any | null
  @column()
  declare excludeCountries: any | null
  @column()
  declare geoTarget: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare intervalMinutes: number | null
  @column()
  declare protocol: string
  @column()
  declare proxyListId: number
  @column()
  declare rotationType: string
  @column()
  declare stickyDurationMinutes: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ScraperRunSchema extends BaseModel {
  static $columns = ['checkMode', 'createdAt', 'createdCount', 'duplicateCount', 'enqueuedCount', 'errorMessage', 'finishedAt', 'id', 'invalidCount', 'meta', 'proxyListId', 'scheduleCron', 'scrapedTotal', 'scraperSourceId', 'sourceKey', 'sourceName', 'startedAt', 'status', 'targetListName', 'teamId', 'triggerType', 'updatedAt', 'updatedCount'] as const
  $columns = ScraperRunSchema.$columns
  @column()
  declare checkMode: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdCount: number
  @column()
  declare duplicateCount: number
  @column()
  declare enqueuedCount: number
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invalidCount: number
  @column()
  declare meta: any | null
  @column()
  declare proxyListId: number | null
  @column()
  declare scheduleCron: string | null
  @column()
  declare scrapedTotal: number
  @column()
  declare scraperSourceId: number | null
  @column()
  declare sourceKey: string
  @column()
  declare sourceName: string
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column()
  declare targetListName: string | null
  @column()
  declare teamId: number
  @column()
  declare triggerType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedCount: number
}

export class ScraperSourceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isEnabled', 'lastCount', 'lastRunAt', 'name', 'proxyListId', 'scheduleCron', 'sourceKey', 'teamId', 'updatedAt'] as const
  $columns = ScraperSourceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isEnabled: boolean
  @column()
  declare lastCount: number
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare proxyListId: number | null
  @column()
  declare scheduleCron: string | null
  @column()
  declare sourceKey: string
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TeamSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'monthlyQuotaBytes', 'name', 'ownerId', 'updatedAt'] as const
  $columns = TeamSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare monthlyQuotaBytes: bigint | number | null
  @column()
  declare name: string
  @column()
  declare ownerId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'currentTeamId', 'email', 'emailVerifiedAt', 'fullName', 'id', 'password', 'roleId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentTeamId: number | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare roleId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
