# RabbitMQ Configuration
default_vhost = proxysystem
loopback_users.guest = false
load_definitions = /etc/rabbitmq/definitions.json

# Memory & disk
vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 1GB

# Logging
log.console = true
log.console.level = warning
log.file = false
